/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.ingsis.starships

import junit.framework.Assert.assertNotNull
import org.junit.Test


class AppTest {
    @Test
    fun appHasAGreeting() {
       // val classUnderTest = App()
      //  assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
